FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml .env ./
COPY ./src/ ./src/

RUN pip install --upgrade pip
RUN pip install -e ".[dev]"

EXPOSE 8000

CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]