FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml .env ./
COPY ./src/ ./src/

RUN apt-get update
RUN apt-get install -y --no-install-recommends libpq-dev && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install -e ".[dev]"

EXPOSE 8000

CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]